# Generated by Django 5.2.3 on 2025-08-12 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cricketapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The headline of the news article.", max_length=250
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The main body/content of the news article."
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time of the article.",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="The publication status of the article. Checked means Published.",
                    ),
                ),
            ],
            options={
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
                "ordering": ["-date"],
            },
        ),
    ]
