# Generated by Django 5.2.3 on 2025-09-08 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cricketapp", "0002_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="current_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_players",
                to="cricketapp.team",
            ),
        ),
    ]
