# Generated by Django 5.2.3 on 2025-11-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0004_newsarticle_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowler_matches', to='cricketapp.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='current_non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_striker_matches', to='cricketapp.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='current_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='striker_matches', to='cricketapp.player'),
        ),
    ]
