# Generated by Django 5.2.3 on 2025-11-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0005_match_current_bowler_match_current_non_striker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='max_overs',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
