# Generated by Django 5.2.3 on 2025-11-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0006_match_max_overs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_team',
        ),
        migrations.AddField(
            model_name='player',
            name='past_teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='past_players', to='cricketapp.team'),
        ),
    ]
